package view;

/**
 *
 * @author raiss
 */
public class CadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public CadastroFuncionario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cadastroNomeEmpresa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cadastroEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cadastroSenha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        cadastroConfirmeSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lovelo Black", 0, 16)); // NOI18N
        jLabel2.setText("Hackvara");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 500, 66, 21);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 520, 504, 10);

        jLabel1.setFont(new java.awt.Font("Lovelo Black", 0, 30)); // NOI18N
        jLabel1.setText("Cadastre-se");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(22, 10, 161, 39);

        jLabel3.setFont(new java.awt.Font("Lovelo Black", 1, 16)); // NOI18N
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 140, 60, 21);

        cadastroNomeEmpresa.setFont(new java.awt.Font("Lovelo Black", 0, 16)); // NOI18N
        getContentPane().add(cadastroNomeEmpresa);
        cadastroNomeEmpresa.setBounds(20, 160, 230, 27);

        jLabel4.setFont(new java.awt.Font("Lovelo Black", 1, 16)); // NOI18N
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 210, 50, 21);

        cadastroEmail.setFont(new java.awt.Font("Lovelo Black", 0, 16)); // NOI18N
        getContentPane().add(cadastroEmail);
        cadastroEmail.setBounds(20, 230, 230, 27);

        jLabel5.setFont(new java.awt.Font("Lovelo Black", 1, 16)); // NOI18N
        jLabel5.setText("Senha:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 270, 60, 21);

        cadastroSenha.setFont(new java.awt.Font("Lovelo Black", 0, 16)); // NOI18N
        cadastroSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(cadastroSenha);
        cadastroSenha.setBounds(20, 290, 230, 27);

        jLabel6.setFont(new java.awt.Font("Lovelo Black", 1, 16)); // NOI18N
        jLabel6.setText("Confirme sua senha:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 340, 170, 21);

        cadastroConfirmeSenha.setFont(new java.awt.Font("Lovelo Black", 0, 16)); // NOI18N
        getContentPane().add(cadastroConfirmeSenha);
        cadastroConfirmeSenha.setBounds(20, 360, 230, 27);

        jButton1.setFont(new java.awt.Font("Lovelo Black", 1, 12)); // NOI18N
        jButton1.setText("CONFIRMAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 410, 230, 34);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tela cadastro funcionario.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-80, 0, 480, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        telaFuncionario tela = new telaFuncionario();
        tela.setVisible(true);

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cadastroSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cadastroConfirmeSenha;
    private javax.swing.JTextField cadastroEmail;
    private javax.swing.JTextField cadastroNomeEmpresa;
    private javax.swing.JPasswordField cadastroSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
