
package view;

//import controller.ControllerProdutoDB;
//import java.util.ArrayList;
//import javax.swing.table.DefaultTableModel;
//import model.ModelPessoa;
//import model.ModelProduto;
///**
// * @author matheus.schramm
// */
public class ConsultaProduto extends javax.swing.JFrame {
//    
//  ControllerProdutoDB produtodb = new ControllerProdutoDB();
    
    /**
     * Creates new form ViewConsultaProduto
     */
    public ConsultaProduto(java.awt.Frame parent, boolean modal) {
//        //super(parent, modal);
//        initComponents();
//
//        
//        // coloca a tela no centro
//        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDadosProduto = new javax.swing.JTable();
        edtPesquisaProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("COSULTA DO PRODUTO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 282, 29);

        btnPesquisar.setFont(new java.awt.Font("Dosis", 1, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(729, 99, 100, 33);

        tabelaDadosProduto.setFont(new java.awt.Font("Dosis", 1, 12)); // NOI18N
        tabelaDadosProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Descrição", "Preço"
            }
        ));
        tabelaDadosProduto.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tabelaDadosProduto);
        tabelaDadosProduto.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(22, 151, 806, 351);
        getContentPane().add(edtPesquisaProduto);
        edtPesquisaProduto.setBounds(22, 100, 701, 33);

        jLabel3.setFont(new java.awt.Font("Lovelo Black", 0, 16)); // NOI18N
        jLabel3.setText("Hackvara");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(800, 20, 66, 21);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(22, 45, 806, 14);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tela consulta produto.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 870, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
       listarTodosRegistros();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
//     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    private void listarTodosRegistros() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JTextField edtPesquisaProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelaDadosProduto;
    // End of variables declaration//GEN-END:variables

//    private void listarTodosRegistros() {
//        DefaultTableModel modelo = (DefaultTableModel) tabelaDadosProduto.getModel();
//         
//        modelo.setRowCount (0);
//        // Lista todas as pessoas da classe pessoadb
//        ArrayList<ModelProduto> produto = produtodb.getTodos();
//
//        // Percorre a lista de pessoas recebidas e adiciona na tabela da tela
//     
//
//     for (ModelProduto auxProduto : produto) {
//            modelo.addRow(new Object[]{
//                auxProduto.getCodigo(),
//                auxProduto.getDescricao(),
//                auxProduto.getPreco()
//                
//            });
//        }
          
}
