package view;

/**
 *
 * @author raiss
 */
public class LoginFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginFuncionario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtEmailLogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edtSenhaLogin = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        btncadastr = new javax.swing.JButton();
        btncadastr1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lovelo Black", 0, 16)); // NOI18N
        jLabel1.setText("Hackvara");

        jToggleButton1.setText("jToggleButton1");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lovelo Black", 0, 16)); // NOI18N
        jLabel2.setText("Hackvara");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 390, 66, 21);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 410, 510, 20);

        jLabel3.setFont(new java.awt.Font("Lovelo Black", 0, 30)); // NOI18N
        jLabel3.setText("Login FUNCIONARIO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 289, 39);

        jLabel4.setFont(new java.awt.Font("Dosis", 1, 16)); // NOI18N
        jLabel4.setText("ID ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 120, 20, 21);

        edtEmailLogin.setFont(new java.awt.Font("Dosis", 1, 16)); // NOI18N
        edtEmailLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEmailLoginActionPerformed(evt);
            }
        });
        getContentPane().add(edtEmailLogin);
        edtEmailLogin.setBounds(140, 150, 259, 27);

        jLabel5.setFont(new java.awt.Font("Dosis", 1, 16)); // NOI18N
        jLabel5.setText("Senha:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 200, 55, 21);

        edtSenhaLogin.setFont(new java.awt.Font("Dosis", 1, 16)); // NOI18N
        getContentPane().add(edtSenhaLogin);
        edtSenhaLogin.setBounds(140, 230, 259, 27);

        jLabel6.setFont(new java.awt.Font("Dosis", 2, 14)); // NOI18N
        jLabel6.setText("Não esta cadastrado? ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 350, 144, 19);

        btncadastr.setFont(new java.awt.Font("Dosis", 1, 16)); // NOI18N
        btncadastr.setText("Cadastre-se!");
        btncadastr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrActionPerformed(evt);
            }
        });
        getContentPane().add(btncadastr);
        btncadastr.setBounds(210, 370, 140, 30);

        btncadastr1.setFont(new java.awt.Font("Dosis", 1, 16)); // NOI18N
        btncadastr1.setText("Confirmar");
        btncadastr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastr1ActionPerformed(evt);
            }
        });
        getContentPane().add(btncadastr1);
        btncadastr1.setBounds(140, 296, 260, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tela login funcionario.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 560, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtEmailLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEmailLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEmailLoginActionPerformed

    private void btncadastrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrActionPerformed
        CadastroEmpresa tela = new CadastroEmpresa();
        tela.setVisible(true);

        dispose();
    }//GEN-LAST:event_btncadastrActionPerformed

    private void btncadastr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastr1ActionPerformed
        telaFuncionario tela = new telaFuncionario();
        tela.setVisible(true);

        dispose();
    }//GEN-LAST:event_btncadastr1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncadastr;
    private javax.swing.JButton btncadastr1;
    private javax.swing.JTextField edtEmailLogin;
    private javax.swing.JPasswordField edtSenhaLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
